#!/bin/bash

gen_password(){
    < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c6
}

gen_password_hash(){
    local password
    password="$1"
    printf "%s" "${password}" | openssl passwd -1 -stdin
}

main(){
    local users=()
    local password
    local password_hash

    # needs to be ran as root
    if [[ "$UID" != "0" ]]; then
        printf "This script must be ran as root, attempting sudo...\\n"
        exec sudo -- "$0" "$@"
    fi

    # read file
    mapfile -t users < "$1"

    printf "\\n"
    for user in "${users[@]}"; do
        password="$(gen_password)"
        password_hash="$(gen_password_hash "${password}")"
        printf "User: %s\\n" "${user}"
        printf "Random Password: %s\\n" "${password}"

        printf "Adding User: "
        if useradd --create-home --shell /bin/bash --password "${password_hash}" "${user}"; then
            printf "Okay\\n"
        else
            printf "Fail\\nAborting...\\n"
            exit 1
        fi 

        printf "Expiring Password: "
        if chage -d 0 "${user}"; then
            printf "Okay\\n"
        else
            printf "Fail\\nAborting...\\n"
            exit 1
        fi   
        printf "\\n"
    done

}
main "$@"
